### ISSUE TITLE
Determinant computation fails

### ISSUE THREAD

**Issue by cfhammill** [derekbeaton/outlieRs#1]
When there are a large number of eigenvalues (in my case 331) the min determinant comes out to zero, the product underflows. This could be remedied by working with log scale eigenvalues.

**Comment by derekbeaton** [comment]
Thanks for bringing this to our attention! In a separate package we have developed (which will eventually replace outlieRs), we use the geometric mean of eigenvalues so we can avoid these issues. 

For now, I'll make that change in mcd.boot.pipeline so we don't run into this issue again.
